<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pc</string>
	</array>
	<key>name</key>
	<string>paperclip</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#xexpressions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>sblock</key>
		<dict>
			<key>begin</key>
			<string>\{\{[#/]?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.tagOpen.paperclip</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.tagOpen.paperclip</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sscript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sexpressions</string>
				</dict>
			</array>
		</dict>
		<key>sexpressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#snumber</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sstring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sreserved</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sreference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#smodifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#soperator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sobject</string>
				</dict>
			</array>
		</dict>
		<key>smodifier</key>
		<dict>
			<key>begin</key>
			<string>\|\s*\w+\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.paperclip</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.paperclip</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sexpressions</string>
				</dict>
			</array>
		</dict>
		<key>snumber</key>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.paperclip</string>
		</dict>
		<key>sobject</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sexpressions</string>
				</dict>
			</array>
		</dict>
		<key>soperator</key>
		<dict>
			<key>match</key>
			<string>[-+|=*%]</string>
			<key>name</key>
			<string>keyword.operator.paperclip</string>
		</dict>
		<key>sreference</key>
		<dict>
			<key>match</key>
			<string>\b(\w+)(\.\w+)*\b</string>
			<key>name</key>
			<string>variable.other.paperclip</string>
		</dict>
		<key>sreserved</key>
		<dict>
			<key>match</key>
			<string>\s*(true|false|null|undefined)\s*</string>
			<key>name</key>
			<string>constant.language.paperclip</string>
		</dict>
		<key>sscript</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.paperclip</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+):</string>
		</dict>
		<key>sstring</key>
		<dict>
			<key>begin</key>
			<string>['"]+</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.paperclip</string>
				</dict>
			</dict>
			<key>end</key>
			<string>['"]+</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.paperclip</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>string.quoted.single.paperclip</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^'"]+</string>
					<key>name</key>
					<string>string.quoted.single.paperclip</string>
				</dict>
			</array>
		</dict>
		<key>xattrexpressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#xattrdatabind</string>
				</dict>
			</array>
		</dict>
		<key>xattribute</key>
		<dict>
			<key>begin</key>
			<string>\s*([_\-\w]+)\=(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.paperclip</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.begin.paperclip</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.end.paperclip</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^"{]+</string>
					<key>name</key>
					<string>string.quoted.single.paperclip</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sblock</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\{</string>
					<key>name</key>
					<string>string.quoted.single.paperclip</string>
				</dict>
			</array>
		</dict>
		<key>xattributeNoValue</key>
		<dict>
			<key>match</key>
			<string>\s*([_\-\w]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.paperclip</string>
		</dict>
		<key>xclosetag</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.paperclip</string>
				</dict>
			</dict>
			<key>match</key>
			<string>&lt;/(\w+)&gt;</string>
		</dict>
		<key>xcomment</key>
		<dict>
			<key>match</key>
			<string>&lt;!--.*?--&gt;</string>
			<key>name</key>
			<string>comment.block.paperclip</string>
		</dict>
		<key>xexpressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#xcomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xopentag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xclosetag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sblock</string>
				</dict>
			</array>
		</dict>
		<key>xopentag</key>
		<dict>
			<key>begin</key>
			<string>(&lt;)(\w+)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.paperclip</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.paperclip</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.paperclip</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#xattribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xattributeNoValue</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.paperclip</string>
	<key>uuid</key>
	<string>e289723a-1c1e-4d87-98f6-dae5efd97e91</string>
</dict>
</plist>
